# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: spw

builds:
  - main: ./cmd/spw/
    binary: spw
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

# Uncomment after creating HOMEBREW_TAP_TOKEN secret and homebrew-tap repo:
# brews:
#   - name: spw
#     description: "SPW — spec-workflow command kit for Claude Code"
#     homepage: "https://github.com/lucas-stellet/spw"
#     license: "MIT"
#     repository:
#       owner: lucas-stellet
#       name: homebrew-tap
#     directory: Formula
#     commit_author:
#       name: lucas-stellet
#       email: lustepe@gmail.com
#     install: |
#       bin.install "spw"
#     test: |
#       system "#{bin}/spw", "version"
